source 'https://github.com/WyICSP/WFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'

target 'WFStatistics_Example' do
  pod 'WFStatistics', :path => '../'

  target 'WFStatistics_Tests' do
    inherit! :search_paths

    
  end
end
